@extends('layouts.app', ['title' => 'Student profile'])

@section('content')
<div class="mx-auto max-w-4xl">
    <div class="mb-8 flex items-end justify-between gap-4"><div><p class="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-indigo-600">Directory profile</p><h1 class="text-3xl font-bold tracking-tight text-slate-950">Student profile</h1></div><a href="{{ route('students.index') }}" class="hidden rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600 shadow-sm transition hover:border-indigo-200 hover:text-indigo-700 sm:block">← Back to directory</a></div>
    <article class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl shadow-slate-200/50">
        <div class="bg-slate-950 px-6 py-8 text-white sm:px-10"><div class="flex flex-col items-start gap-6 sm:flex-row sm:items-center"><div class="relative flex h-28 w-28 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-indigo-500/30 font-display text-2xl font-bold text-indigo-200 ring-4 ring-white/10">{{ $student->initials }}<img src="{{ asset('storage/' . $student->profile_picture) }}" alt="Profile picture of {{ $student->first_name }} {{ $student->last_name }}" class="absolute inset-0 h-full w-full object-cover" onerror="this.remove()"></div><div><div class="mb-3 flex flex-wrap gap-2"><span class="rounded-full bg-indigo-400/20 px-3 py-1 text-xs font-bold text-indigo-200">{{ $student->program }}</span><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-slate-200">{{ $student->year_level }}</span></div><h2 class="text-3xl font-bold">{{ $student->first_name }} {{ $student->middle_name }} {{ $student->last_name }}</h2><p class="mt-2 text-sm text-slate-400">Student ID <span class="font-semibold text-slate-200">{{ $student->student_id }}</span></p></div></div></div>
        <div class="grid gap-x-8 gap-y-7 p-6 sm:grid-cols-2 sm:p-10"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Email address</p><p class="mt-1 break-all font-semibold text-slate-800">{{ $student->email }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Mobile number</p><p class="mt-1 font-semibold text-slate-800">{{ $student->mobile_number }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Date of birth</p><p class="mt-1 font-semibold text-slate-800">{{ $student->date_of_birth->format('F j, Y') }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Gender</p><p class="mt-1 font-semibold text-slate-800">{{ $student->gender }}</p></div><div class="border-t border-slate-100 pt-6 sm:col-span-2"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Complete address</p><p class="mt-1 font-semibold leading-6 text-slate-800">{{ $student->address }}</p></div></div>
    </article>
    <a href="{{ route('students.create') }}" class="mt-6 block text-center text-sm font-bold text-indigo-600 hover:text-indigo-800 sm:hidden">← Register another student</a>
</div>
@endsection